phantomx:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------


  # HEAD
  head_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - j_c1_lf
      - j_c1_lm
      - j_c1_lr
      - j_c1_rf
      - j_c1_rm
      - j_c1_rr
      - j_thigh_lf
      - j_thigh_lm
      - j_thigh_lr
      - j_thigh_rf
      - j_thigh_rm
      - j_thigh_rr
      - j_tibia_lf
      - j_tibia_lm
      - j_tibia_lr
      - j_tibia_rf
      - j_tibia_rm
      - j_tibia_rr
    allow_partial_joints_goal: true



    

  j_pan_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_pan
    pid: {p: 100.0, i: 0.01, d: 10.0}

  j_tilt_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_tilt
    pid: {p: 100.0, i: 0.01, d: 10.0}


  # ARMS

  j_shoulder_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_shoulder_l
    pid: {p: 100.0, i: 0.01, d: 10.0}

  j_high_arm_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_high_arm_l
    pid: {p: 100.0, i: 0.01, d: 10.0}

  j_low_arm_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_low_arm_l
    pid: {p: 100.0, i: 0.01, d: 10.0}

  j_wrist_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_wrist_l
    pid: {p: 100.0, i: 0.01, d: 10.0}

  j_gripper_l_position_controller:
    type: effort_controllers/JointPositionController
    joint: j_gripper_l
    pid: {p: 100.0, i: 0.01, d: 10.0}


