phantomx:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 5
  
  # Position/Velocity Controllers ---------------------------------------
  trajectory_controller_for_single_step:
    type: velocity_controllers/JointTrajectoryController
    joints:
      - j_c1_lf
      - j_c1_lm
      - j_c1_lr
      - j_c1_rf
      - j_c1_rm
      - j_c1_rr
      - j_thigh_lf
      - j_thigh_lm
      - j_thigh_lr
      - j_thigh_rf
      - j_thigh_rm
      - j_thigh_rr
      - j_tibia_lf
      - j_tibia_lm
      - j_tibia_lr
      - j_tibia_rf
      - j_tibia_rm
      - j_tibia_rr
    allow_partial_joints_goal: true
    constraints:
      goal_time: 10.0
    gains: # Required because we're controlling an effort interface
      j_c1_lf: {p: 99,   i: 0, d: 0 } #, i_clamp: 1
      j_c1_lm: {p: 99,   i: 0, d: 0 } #, i_clamp: 1
      j_c1_lr: {p: 99,   i: 0, d: 0 } #, i_clamp: 1
      j_c1_rf: {p: 99,   i: 0, d: 0 } #, i_clamp: 1
      j_c1_rm: {p: 99,   i: 0, d: 0 } #, i_clamp: 1
      j_c1_rr: {p: 99,   i: 0, d: 0 } #, i_clamp: 1
      j_thigh_lf: {p: 99,   i: 0, d: 0 } #, i_clamp: 1
      j_thigh_lm: {p: 99,   i: 0, d: 0 } #, i_clamp: 1
      j_thigh_lr: {p: 99,   i: 0, d: 0 } #, i_clamp: 1
      j_thigh_rf: {p: 99,   i: 0, d: 0 } #, i_clamp: 1
      j_thigh_rm: {p: 99,   i: 0, d: 0 } #, i_clamp: 1
      j_thigh_rr: {p: 99,   i: 0, d: 0 } #, i_clamp: 1
      j_tibia_lf: {p: 99,   i: 0, d: 0 } #, i_clamp: 1
      j_tibia_lm: {p: 99,   i: 0, d: 0 } #, i_clamp: 1
      j_tibia_lr: {p: 99,   i: 0, d: 0 } #, i_clamp: 1
      j_tibia_rf: {p: 99,   i: 0, d: 0 } #, i_clamp: 1
      j_tibia_rm: {p: 99,   i: 0, d: 0 } #, i_clamp: 1
      j_tibia_rr: {p: 99,   i: 0, d: 0 } #, i_clamp: 1
